name: template_first
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.4
  get_it: ^7.6.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
